flekschas/regl-scatterplot

CHANGELOG.md
src/lasso-manager/index.js

When the scatterplot is within an element with some margin/padding to the top and the page is scrollable, then the lasso was misplaced. This has to do that the lasso being drawn relative to the canvas and not to the window. Removing window.scrollX/Y lets the lasso be drawn regardless of how far you have scrolled

fix mousePosition

---

src/index.js

this fixes a small bug where the `pointout` event is not emitted when the point in question is part of the selected set

Fix pointer out event

---

src/types.d.ts

'select' is a valid event name, when a selection of points has been made.

Add a missing event name

---

CHANGELOG.md
src/index.js

This PR attempts to fix the point hovering issue described in #112.
Previously we initialized `isMouseInCanvas` as `false`. The `isMouseInCanvas` is making sure that we don't do unnecessary computations if the user mouses around outside the scatterplot. However, in the edge case where the scatterplot instance was initialized when the mouse was already over the canvas element, the mouse enter handler would never fire and `isMouseInCanvas` would never be set to true. That prevented hover effects from working.
This PR fixes this by checking which elements the mouse is hovering on the initial mouse move event.
Fixes #112

fix: correctly check if mouse is over the canvas element

---

CHANGELOG.md
src/types.d.ts

Added typing support for EventMap select event
Fixes [#119](https://github.com/flekschas/regl-scatterplot/issues/119)
- [] Screenshot, gif, or video attached for visual changes

fix: improve typing of the select event

---

CHANGELOG.md
README.md
src/constants.js
src/index.js
src/types.d.ts
tests/index.js

This PR supersedes https://github.com/flekschas/regl-scatterplot/pull/124 by adding the necessary changes to make the test pass.
Throw an error when `zoomToPoints()` is called before points have been drawn. Expose `isDestroyed` and `isPointsDrawn` via `get()`.
Fixes #123

fix: zoomToPoints() when no points were drawn yet

---

CHANGELOG.md
README.md
src/index.js
src/types.d.ts
tests/index.js
tests/utils.js

This PR enables filtering out all points by calling `scatterplot.filter([])`;
This PR enables filtering out all points which was previously not possible. To check if any point filter have been applied, this PR also exposes `isPointsFiltered` via the `get()` function.
Fixes #122

fix: allow to filter out all points by calling `filter([])`

---

CHANGELOG.md
src/index.js
tests/index.js

This PR fixes an empty selection call (e.g., `select([])`)
Previously, if the current selection was not empty and the new selection was empty, we accidentally updated the current selection to `[]` prior to calling `deselect([])`. This prevented (a) the `deselect` event from firing and (b) didn't properly re-render the plot. Now, we're not going to set `deselect()` handle the setting of the current selection to properly call the `deselect` event and trigger a re-rendering of the plot.
Fixes #132

fix: empty selection handling of `select([])`

---

src/types.d.ts

Fixes #[138](https://github.com/flekschas/regl-scatterplot/issues/138)

fix: filteredPoints not in gettable scatter properties

---

README.md
src/index.js
src/types.d.ts
tests/index.js

Adds `preventFilterReset` option to `ScatterplotMethodOptions['draw']` to allow re-drawing while keeping the current active filter.
- Added `preventFilterReset` option to `ScatterplotMethodOptions['draw']`
Fixes #136

fix: Inability to draw with active filter

---

CHANGELOG.md
src/index.js
tests/index.js

This PR ensures that a single line connecting all points is drawn correctly.
Previously, when one attempted to draw a single point connection that connects all points, no line would be drawn. This is now working.
As part of this fix, I also fixed the `draw()` functions resolution to await the drawing of point connections (when `showPointConnections` is set to `true`). Previously, `draw()` would resolve as soon as the points were drawn but drawing lines typically takes longer. Hence, `draw()` resolved too early. With this PR, when `showPointConnections` is `true`, `draw()` will resolve after both, the points and the connections, have been drawn.
Fixes #125

fix: drawing a single connecting line between points

---

CHANGELOG.md
README.md
src/index.js
src/types.d.ts
tests/index.js

This PR adds the ability to hover, select, and filter points at the time when `draw()` is called.
I added three new properties to the draw options: `hover`, `select`, and `filter`. Those options allow to immediately hover, select, or filter points as they are drawn. E.g.:
```js
const points = [[0, 0], [0.5, 0.5], [1, 1]];
scatterplit.draw(points, { hover: 0, select: [0, 2], filter: [0, 1] });
```
In the above example, upon drawing the three points, the first point is hovered and selected and the last point is filtered out. While we also attempted to select the last point it's not going to be selected because we filter it out.
For convenience, this PR also expose `hoveredPoint` via `scatterplot.get('hoveredPoint')`. …

feat: add ability to hover, select, and filter points upon `draw()`

---

CHANGELOG.md
src/index.js
src/types.d.ts

This PR fixes types and enables setting the aspect ratio in the constructor
- Add ability to set `aspectRatio` in the constructor
- Add type for `aspectRatio`
- Fix type of `opacity`
Fixes #146

fix: aspect ratio and opacity types

---

CHANGELOG.md
README.md
example/text-labels.js
package-lock.json
package.json
src/index.js
src/types.d.ts
tests/index.js

This PR adds a new event called `drawing` whose callback listeners are _always_ triggered synchronously. In addition, this PR fixes a discrepancy of the `draw` event payload between the docs and implementation.
1. Introduced a new `drawing` event that is fired at the end of the draw call before the draw call finished.
2. Exposed `{ camera, view, xScale, yScale }` as the payload of the `draw` event.
The new `drawing` event allows for rendering other things as part of the same animation frame. Previously this was only possible if regl-scatterplot was created with the `syncEvents` option. This option, however, has the negative side effect of making all event callback listeners fire synchronously, which is not advisable.
E.g., …

add: new `drawing` event

---

CHANGELOG.md
src/index.js
tests/index.js

This PR fixes two issues related point filtering
1. After filter out some points, trying to programmatically hover them with `scatterplot.hover(filteredOutPointIdx)` will not work anymore
2. When re-drawing points with `preventFilterReset: true`, the point index buffer will not be recreated to persist the current filter state
Here's an example showing the `scatterplot.draw(newPoints, { preventFilterReset: true })` works as intended now
https://github.com/flekschas/regl-scatterplot/assets/932103/e5e8ae77-d311-4740-af8e-9bbbc01f7ba6
I simulated this with the basic example using:
```js
setTimeout(() => {
scatterplot.filter(
scatterplot
.get('points')
.map((point, i) => [point, i])
.filter(([point]) => point[0] >= 0)
.map(([_, i]) => i)
); …
```

fix: two issues related to point filtering

---

CHANGELOG.md
README.md
example/annotations.js
package-lock.json
package.json
src/index.js
src/kdbush.js
src/types.d.ts

This PR fixes the KDBush worker in the production build.
To avoid name clashes, the worker now depends on a named function declaration.
Previously it was possible that due to bundling and code minimization, the class `KDBush` was renamed. Since the worker function didn't know about this, the KDBush worker ultimately failed.
Fixes #189

fix: kdbush worker

---

example/index.js
public/index.html
src/constants.js
src/index.js

> Write one to two sentences summarizing this PR
This introduces two new modes: 
(1) point size is kept constant, independent of zoom
(2) point size is proportional to zoom.
- the getPointScale method in index.js
- an additional attribute POINT_SCALE_MODE was introduced, which allows to switch between three modes: 'constant', 'proportional' and 'default. 
Fixes #169

feat: add support for linear and constant point scaling via a new property called `pointScaleMode`

---

CHANGELOG.md
biome.json
src/index.js
src/utils.js
tests/index.js

This PR fixes the stacking issues when filtering points
This PR ensures that the order of points to be filtered cannot be altered externally. E.g., `scatterplot.filter([0, 1])` and `scatterplot.filter([1, 0])` is now going to give the same results. Previously, the order of point IDs defined the drawing order.
Fixes #197 
> Example
Following the example from https://github.com/flekschas/regl-scatterplot/issues/197, when filtering by `scatterplot.filter([0, 1])`, the following happened:
**Previously**
https://github.com/user-attachments/assets/26cda31c-f1b1-49ba-9b04-6279bc9c4582
**Now**
https://github.com/user-attachments/assets/b75ea728-c29e-4bbf-aeab-f9d209209dcd

fix: filter stacking bug

---

CHANGELOG.md
src/index.js
tests/get-set.test.js

This PR fixes another edge case where `zoomToOrigin` was unsetting the camera fixed state.
`zoomToLocation` (and `zoomToOrigin` as a consequence) had accidentally unset the camera fixed state. Now they respect the `cameraIsFixed` setting

fix: edge case where `zoomToOrigin` unsets the fixed camera

---

CHANGELOG.md
README.md
src/constants.js
src/index.js
src/point.fs
src/point.vs
src/renderer.js
src/types.d.ts
tests/methods.test.js

This PR improves `scatterplot.export()` by allowing to customize the rendering settings during the export.
- Added `antiAliasing` property to allow adjusting the anti-aliasing of points
- Added `pixelAligned` property to allow aligning points with the pixel grid
- Enhanced `export()` to allow up or down scaling the exported image as well as adjusting the anti-aliasing and pixel alignment settings during export
- Exposed the renderer's `resize()` function in case one wants to resize the renderer's canvas.
Fixes #175
All changes enable better exporting. E.g., during export it can be useful to upscale the image, render the points a tad smoother by increasing the anti-aliasing and snapping points to the pixel grid.
Huge thanks go …

feat: improve export functionality

---

CHANGELOG.md
src/constants.js
src/index.js
src/utils.js
tests/events.test.js
tests/get-set.test.js
tests/methods.test.js
tests/utils.js

This PR fixes the WebGL texture bug that appears when one frequently changed the point encoding (point color, size, and opacity)
- Fix: destroy the encoding texture before recreating it
- Fix: reject `set()` calls if the instance was destroyed
- Fix: ensures unnecessary color and encoding texture updates are avoided
- Fix: color and encoding textures are destroyed upon calling `scatterplot.destroy()`
- Fix: prevent a minor memory leak in the newly added advanced exporter
Fixes #165 
> Example
**Before**
After ~30 draw calls the WebGL described in #165 appears:
https://github.com/user-attachments/assets/600f4f7b-a4f3-4a9e-aa5c-15bb543b1534
**After**
With this fix, the error does not appear: …

fix: prevent premature draw calls and destroy encoding texture prior to recreation

---

CHANGELOG.md
src/index.js

This PR ensures that when the number of points to be drawn is zero, the points draw is skipped.
1. Skip drawing points if there aren't any to draw
2. Ensure that `scatterplot.filter()` only treats finite numbers as valid indices (i.e., `scatterplot.filter([])` and `scatterplot.filter([undefined])` behave identical now)
Fixes #201 
> Examples
**Before**
https://github.com/user-attachments/assets/19715714-3f3c-4ad0-bf81-0c76b199752a
**After**
https://github.com/user-attachments/assets/fa66f87e-4be8-4ccd-a2f3-081b7a2f28f9

Fix: prevent drawing points if all are filtered out

---

CHANGELOG.md
README.md
src/index.js
src/types.d.ts
tests/get-set.test.js

Expose `renderPointsAsSquares` and `disableAlphaBlending` to allow finer control over performance increasing settings.
Added two props:
1. `renderPointsAsSquares`
2. `disableAlphaBlending`
Note that if `performanceMode` is `true`, both props are automatically true.
Fixes #206 
> Examples
**Normal**
**No Alpha Blending**
**Squared Points**

feat: add `renderPointsAsSquares` and `disableAlphaBlending`

---

CHANGELOG.md
README.md
src/index.js
src/kdbush.js

This PR exposes `isViewChanged` in the payload of `draw`, `drawing`, and `view` events
- Exposes `isViewChanged` in the payload of `draw`, `drawing`, and `view` events
- Clean up worker URL after creation
To make it easier for consumers to know whether a draw call was triggered by a view change

feat: expose if view has changed
